### ISSUE TITLE
Beta 版本相关问题汇总

### ISSUE THREAD

**Issue by alvinhui** [appworks-lab/toolkit#5]
Buglist:

- [x] 第二次进行「一键安装」的时候，之前的日志没有清空 [image](https://user-images.githubusercontent.com/4392234/119610459-dae14680-be2b-11eb-872f-339225be5f07.png)
- [x] AppWorks 单词大小写问题和 AppWorks 描述优化 [image1](https://user-images.githubusercontent.com/4392234/119616996-e3d61600-be33-11eb-9460-607438a9449e.png) / [image2](https://user-images.githubusercontent.com/4392234/119617500-8098b380-be34-11eb-968f-3938c4d3783a.png)
- [x] Node 版本管理功能，切换版本后返回管理页面，Node 版本号还是旧的 [image](https://user-images.githubusercontent.com/4392234/119621499-c8b9d500-be38-11eb-871f-07c9e6bbddff.png)

P0: 正式版本前必须修复(6.3)

- [x] 获取所有 Node.js 版本时间过慢，可以考虑添加缓存到本地 https://github.com/appworks-lab/toolkit/issues/5#issuecomment-848780975 @alvinhui 
- [x] 一键安装的过程中的安装列表在切换后出现变化 https://github.com/appworks-lab/toolkit/issues/5#issuecomment-851327964
- [x] 切换 Node 版本的表单优化 https://github.com/appworks-lab/toolkit/issues/5#issuecomment-851331735
- [x] 切换 Node 版本的问题 https://github.com/appworks-lab/toolkit/issues/5#issuecomment-851345762
- [x] 工具列表添加跳转链接 https://github.com/appworks-lab/toolkit/issues/5#issuecomment-851367118 @alvinhui 
 
P1: 

- [ ] 安装套件时间过慢 https://github.com/appworks-lab/toolkit/issues/5#issuecomment-848532775
- [x] 多个 profile 共存时，虽然 nvm 已经安装到本地，但 Toolkit 提示没有安装 https://github.com/appworks-lab/toolkit/issues/5#issuecomment-848540852
- [ ] 应用第一次启动时，弹窗让用户输入密码，并保存密码(加密后的密码)至本地，避免后面需要操作权限时多次弹窗询问用户权限

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/119610459-dae14680-be2b-11eb-872f-339225be5f07.png)

第二次进行「一键安装」的时候，日志没有清空。

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/119616996-e3d61600-be33-11eb-9460-607438a9449e.png)

这句话改为：基于 VS Code 的多端研发套件

得显示地声明一下是 VS Code 下的

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/119617500-8098b380-be34-11eb-968f-3938c4d3783a.png)

检查一下，名词统一大写驼峰式：**AppWorks**

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/119618802-e3d71580-be35-11eb-97e4-b8ce4568e30b.png)

安装套件的时候，我第一次安装的时候非常慢，等了五六分钟还没有安装好。
后来我开启了加速，一下子就安装好了。
后续我卸载再安装也很快。
可能 `code` 有缓存机制。

从我们的角度，还是要想办法让这一过程更快。
我是比较建议说后续不依赖 `code` 命令行去实现这一功能。
就看看投入产出比了。

**Comment by alvinhui** [comment]
本地已安装了 nvm ，但是 toolkit 没有检测到：

![image](https://user-images.githubusercontent.com/4392234/119620834-0702c480-be38-11eb-9902-51bf79085907.png)

![image](https://user-images.githubusercontent.com/4392234/119620767-f4888b00-be37-11eb-93c4-0fb6049a4e75.png)

**Comment by luhc228** [comment]
获取所有 Node.js 版本时间过慢，可以考虑添加缓存到本地
![image](https://user-images.githubusercontent.com/44047106/119670083-2cf58c80-be6b-11eb-85d1-7a8965dafacc.png)

**Comment by alvinhui** [comment]
1. 在首页点击“一键安装”，取消勾选 Git，安装列表里面没有 Git
2. 切换到“Node 管理”，再切换到首页，安装列表里面出现了 Git

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/120167443-55e19d00-c230-11eb-930a-5abf44596bc3.png)

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/120167508-66921300-c230-11eb-843f-9d71db3a3841.png)

这个“重装全局依赖”功能需要说明一下，目前来说大家有点看不懂它的作用。如果是必要的，那么为什么还需要让用户来进行选择？

**Comment by alvinhui** [comment]
切换 Node 版本的时候，没有日志，且最后失败了：

![image](https://user-images.githubusercontent.com/4392234/120169893-fc2ea200-c232-11eb-817e-83721a582644.png)

![image](https://user-images.githubusercontent.com/4392234/120169969-0fda0880-c233-11eb-9bd6-5f685c84c39c.png)

**Comment by alvinhui** [comment]
为列表里的工具添加链接跳转

![image](https://user-images.githubusercontent.com/4392234/120174616-dc4dad00-c237-11eb-90ee-1c30e755dc18.png)

**Comment by luhc228** [comment]
> ![image](https://user-images.githubusercontent.com/4392234/119618802-e3d71580-be35-11eb-97e4-b8ce4568e30b.png)
> 
> 安装套件的时候我这边存在一个现象，操作过程如下：
> 
> * 第一次安装套件，非常慢，等了五六分钟还没有安装好。于是我取消了安装；
> * 然后我开启了网络加速（FQ），再操作安装套件，一下子就安装好了；
> * 后续我本地卸载掉套件，再用 Toolkit 安装，即便是不加速，也很快；
> 
> 我猜测可能 `code` 命令的实现有缓存机制。
> 
> 从我们的角度，还是要想办法让这一过程更稳定更快。
> 我是比较建议说后续不依赖 `code` 命令行去实现这一功能的。
> 但是要看看投入产出比了。


目前的实现方式是通过以下命令安装 VS Code 插件：
```
code --install-extension iceworks-team.iceworks
```

这个命令主要做了几个事情：
1. 下载一个 vsix 到本地
2. 解压 vsix 文件（可理解是 zip）
3. 分析里面的 `extension.vsixmanifest`、`package.json` 文件，收集该插件所依赖的插件（extensionDependencies 和 extensionPack），并重复上面的步骤1和2
4. 修改 `extension.vsixmanifest` 文件的路径，复制解压后的文件夹到 `~/.vscode/extensions/` 目录下
5. 修改 `~/.vsocde/extensions/.obsolete` 文件（用于存放废弃的插件，如果插件 id 在此文件中，则在 vscode 插件市场中不会显示），确保刚才安装的插件 id 不在此文件中

从上面问题描述来看，主要是**从网络下载 vsix 文件的时候比较慢（也就是第1步）**，而其他本地的操作速度理论上都很快。

解决下载慢的问题，可以把 `*.vsix` 放到 oss 上，toolkit 去 oss 上拉取 .vsix 到用户本地。

安装插件有两个方案：

### 方案一
调用 `code --install-extension ./iceworks-team.iceworks-app-1.0.0.vsix` 安装本地 vsix。

优点：借助于 code 命令去管理插件
缺点：目前需要自己实现的一套 Install Code to PATH

### 方案二
自己实现一套类似于 code 的功能去安装/卸载插件。

优点：不需要借助 code 命令，也不需要目前的自己实现的一套 Install Code to PATH
缺点：管理插件的实现还是有挺大的成本，看了看源码实现需要考虑挺多边界 case

**Comment by alvinhui** [comment]
@luhc228 

方案一是缺点是：
1. 对 code 命令的依赖是不稳定的强依赖，你不了解 code 未来的逻辑变化，例如开发者本地 code 命令升级后参数变了
2. 网络的稳定性，无法指定源

方案二的缺点是:
1. 有实现和维护成本。看看能不能把 code 那个包引过来，例如把代码下载到本地之类。。。
